#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require('luci.model.uci').cursor()

  uci:set('gluon-node-info', uci:get_first('gluon-node-info', 'location'), 'auto_location', site.location.autolocation)
  uci:save('gluon-node-info')
  uci:commit('gluon-node-info')
