#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local config = 'configurator'
local ipv6_address = uci:get(config, uci:get_first(config, 'api'), 'ipv6_address')

if not ( ipv6_address == 'netmon.ffnw' ) then
  uci:set(config, uci:get_first(config, 'api'), 'ipv6_address', 'netmon.ffnw')
  uci:save(config)
  uci:commit(config)
end
